set(output_file /home/lachei/Dokumente/PCViewer/PCViewer/gpu_radix_sort/shaders.h)
file(REMOVE ${output_file})
file(WRITE ${output_file} "#pragma once\n")
file(APPEND ${output_file} "#include <memory_view.hpp>\n")
file(APPEND ${output_file} "namespace ShaderBinaries {\n")
set(binary_files /home/lachei/Dokumente/PCViewer/PCViewer/gpu_radix_sort/shader/compiled_shaders/radix_count_float.comp.spv;/home/lachei/Dokumente/PCViewer/PCViewer/gpu_radix_sort/shader/compiled_shaders/radix_count_int.comp.spv;/home/lachei/Dokumente/PCViewer/PCViewer/gpu_radix_sort/shader/compiled_shaders/radix_count_uint.comp.spv;/home/lachei/Dokumente/PCViewer/PCViewer/gpu_radix_sort/shader/compiled_shaders/radix_count_float_32.comp.spv;/home/lachei/Dokumente/PCViewer/PCViewer/gpu_radix_sort/shader/compiled_shaders/radix_reduce_float.comp.spv;/home/lachei/Dokumente/PCViewer/PCViewer/gpu_radix_sort/shader/compiled_shaders/radix_reduce_int.comp.spv;/home/lachei/Dokumente/PCViewer/PCViewer/gpu_radix_sort/shader/compiled_shaders/radix_reduce_uint.comp.spv;/home/lachei/Dokumente/PCViewer/PCViewer/gpu_radix_sort/shader/compiled_shaders/radix_reduce_float_32.comp.spv;/home/lachei/Dokumente/PCViewer/PCViewer/gpu_radix_sort/shader/compiled_shaders/radix_scan_float.comp.spv;/home/lachei/Dokumente/PCViewer/PCViewer/gpu_radix_sort/shader/compiled_shaders/radix_scan_int.comp.spv;/home/lachei/Dokumente/PCViewer/PCViewer/gpu_radix_sort/shader/compiled_shaders/radix_scan_uint.comp.spv;/home/lachei/Dokumente/PCViewer/PCViewer/gpu_radix_sort/shader/compiled_shaders/radix_scan_float_32.comp.spv;/home/lachei/Dokumente/PCViewer/PCViewer/gpu_radix_sort/shader/compiled_shaders/radix_scan_add_float.comp.spv;/home/lachei/Dokumente/PCViewer/PCViewer/gpu_radix_sort/shader/compiled_shaders/radix_scan_add_int.comp.spv;/home/lachei/Dokumente/PCViewer/PCViewer/gpu_radix_sort/shader/compiled_shaders/radix_scan_add_uint.comp.spv;/home/lachei/Dokumente/PCViewer/PCViewer/gpu_radix_sort/shader/compiled_shaders/radix_scan_add_float_32.comp.spv;/home/lachei/Dokumente/PCViewer/PCViewer/gpu_radix_sort/shader/compiled_shaders/radix_scatter_float.comp.spv;/home/lachei/Dokumente/PCViewer/PCViewer/gpu_radix_sort/shader/compiled_shaders/radix_scatter_int.comp.spv;/home/lachei/Dokumente/PCViewer/PCViewer/gpu_radix_sort/shader/compiled_shaders/radix_scatter_uint.comp.spv;/home/lachei/Dokumente/PCViewer/PCViewer/gpu_radix_sort/shader/compiled_shaders/radix_scatter_float_32.comp.spv)
foreach(binary_file IN LISTS binary_files)
    file(READ ${binary_file} binary_content HEX)
    string(LENGTH "${binary_content}" size)
    set(hex_data)
    while(binary_content MATCHES "..")
        string(SUBSTRING ${binary_content} 0 2 val_hex)
        set(hex_data "${hex_data} 0x${val_hex},")
        string(SUBSTRING ${binary_content} 2 -1 binary_content)
    endwhile()

    file(READ ${binary_file} binary_content HEX)
    get_filename_component(shader_name ${binary_file} NAME_WE)
    file(APPEND ${output_file} "const util::memory_view<const uint8_t> ${shader_name}{(uint8_t[]){${hex_data}}, ${size}/2};\n")
endforeach()
file(APPEND ${output_file} "}\n")
