set(output_file /home/lachei/Dokumente/PCViewer/PCViewer/gpu_radix_sort/shaders.h)
file(REMOVE ${output_file})
file(WRITE ${output_file} "#pragma once\n")
file(APPEND ${output_file} "#include <string_view>\n")
file(APPEND ${output_file} "namespace ShaderBinaries {\n")
set(binary_files /home/lachei/Dokumente/PCViewer/PCViewer/gpu_radix_sort/shader/compiled_shaders/radix_count.comp.spv;/home/lachei/Dokumente/PCViewer/PCViewer/gpu_radix_sort/shader/compiled_shaders/radix_reduce.comp.spv;/home/lachei/Dokumente/PCViewer/PCViewer/gpu_radix_sort/shader/compiled_shaders/radix_scan.comp.spv;/home/lachei/Dokumente/PCViewer/PCViewer/gpu_radix_sort/shader/compiled_shaders/radix_scan_add.comp.spv;/home/lachei/Dokumente/PCViewer/PCViewer/gpu_radix_sort/shader/compiled_shaders/radix_scatter.comp.spv)
foreach(binary_file IN LISTS binary_files)
    file(READ ${binary_file} binary_content HEX)
    string(REGEX REPLACE "([^\n])" "\\\\x\\1" hex_data "${binary_content}")
    get_filename_component(shader_name ${binary_file} NAME_WE)
    file(APPEND ${output_file} "const std::string_view ${shader_name} = \n")
    file(APPEND ${output_file} "    \"${hex_data}\";\n")
endforeach()
file(APPEND ${output_file} "}\n")
